#!/bin/bash

set -e

# Load setup functions
if [ -f "./setupscripts/setup_functions.sh" ]; then
  echo "Found setup scripts"
  . ./setupscripts/setup_functions.sh
else
  echo "Invalid path to setupscripts"
  exit 1
fi

# Write README to temp first
TEMP=$(mktemp)

cat << 'EOF' > "$TEMP"
# Dotfiles

[![test-scripts](https://github.com/aaatipamula/dotfiles/actions/workflows/test.yml/badge.svg)](https://github.com/aaatipamula/dotfiles/actions/workflows/test.yml)
![Shell Script](https://img.shields.io/badge/shell_script-%23121011.svg?style=for-the-badge&logo=gnu-bash&logoColor=white)
![Neovim](https://img.shields.io/badge/NeoVim-%2357A143.svg?&style=for-the-badge&logo=neovim&logoColor=white)
![Vim](https://img.shields.io/badge/VIM-%2311AB00.svg?style=for-the-badge&logo=vim&logoColor=white)

## About

This repo hosts my [dotfiles](https://missing.csail.mit.edu/2019/dotfiles/) for *most* Linux machines and commonly used programs. I also have some setup and helper scripts.

## Setup

Run the two following commands to get started.

\`\`\`bash
git clone https://github.com/aaatipamula/dotfiles.git ~
cd ~/dotfiles && ./setupscripts/setup
\`\`\`

The following options are availabile for \`setup\`:

\`\`\`
$(help_command nocolor)
\`\`\`
EOF

# Only update and re-stage if content changed
if ! diff -q "$README" "$TEMP" > /dev/null 2>&1; then
  mv "$TEMP" "README.md"
  git add "README.md"
  git commit -m "Post-commit update README.md"
fi

exit 0
