#!/bin/bash

# Null check
if [[ -z "$1" ]]; then
  echo "No directory passed to config" >& 2
  exit 1
fi

# Move a directory
if [[ "$1" = "mv" ]]; then
  shift
  path="$XDG_CONFIG_HOME/$1"

  # Directory check
  if [[ ! -d "$path" ]]; then
    echo "$path does not exist!"
    exit 1
  fi

  mv "$path" "$dotfiles/config"
  echo "Moved $path to $dotfiles/config"
  exit 0
fi

# List items in the config directory
if [[ "$1" = "ls" ]]; then
  ls -l --color $XDG_CONFIG_HOME
  exit 0
fi


# Remove a config directory if its symlinked
if [[ "$1" = "rm" ]]; then
  shift
  path="$XDG_CONFIG_HOME/$1"

  # Directory check
  if [[ ! -L "$path" ]]; then
    echo "$path is not a symlinked directory, refusing to remove."
    exit 1
  fi

  rm "$path"
  echo "Removed path $path"
  exit 0
fi

path="$XDG_CONFIG_HOME/$1"

# Open config
if [ -d "$path" ]; then
  $VISUAL "$path" 
elif [ -f "$path" ]; then
  $VISUAL "$path" 
else
  echo -n "No config for $1 found, create directory? [y/n]: "
  read -r choice

  if [[ "$choice" =~ [yY] ]]; then
    mkdir "$path"
    $VISUAL "$path"
  elif [[ "$choice" =~ [nN] ]]; then
    echo "Skipping..."
  fi
fi

