#!/bin/bash

# Default args
input=""
target=""
compiler="gcc"
flags="-Wall -Wextra"
run=false

# Process flags
while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -r|--run)
      echo "Set run true"
      run=true
      shift
      ;;
    +|--cpp)
      compiler="g++"
      shift
      ;;
    --compiler)
      compiler="$2"
      shift 2
      ;;
    --flags)
      flags="$2"
      shift 2
      ;;
    --) # No more flag arguments
      shift
      break
      ;;
    -*)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
    *) # positional argument
      input="$1"
      target="${1%.*}_$(uname)_$(uname -m)"
      shift
      break
      ;;
  esac
done

if [[ -z $input ]]; then
  echo "No input file given" >&2
  exit 1
fi

$compiler $input $flags -o $target

# Run target if asked
if [[ "$run" = true ]]; then
  echo "Running..."
  ./$target
fi

