#!/bin/bash -i

# Set background images folder
BG_IMAGES_FOLDER="$HOME/Pictures/backgrounds"

# Pick image if there is not one provided
if [ -z "$1" ]; then
  img=$(imgpick "$BG_IMAGES_FOLDER")
else
  img=$(realpath "$1")
fi

# Post img
if [ -n "$img" ] && [ -f "$img" ]; then
  ln -sf "$img" ~/.hyprbg
  hyprctl hyprpaper reload ,"$img"
else
  echo "No image selected"
fi

