#!/bin/bash -i

# Set background images folder
BG_IMAGES_FOLDER="$HOME/Pictures/backgrounds"

# Fzf image picker with a preview
imgpick()
{
  local dir="${1:-\.}"
  find "$dir" -type f \( \
       -iname "*.jpg" -o \
       -iname "*.jpeg" -o \
       -iname "*.png" -o \
       -iname "*.gif" -o \
       -iname "*.webp" -o \
       -iname "*.svg" \
     \) \
  | fzf --preview 'fzf-preview.sh {}'
}

# Pick image if there is not one provided
if [ -z "$1" ]; then
  img=$(imgpick "$BG_IMAGES_FOLDER")
else
  img=$(realpath "$1")
fi

# Post img
if [ -n "$img" ] && [ -f "$img" ]; then
  ln -sf "$img" ~/.hyprbg
  hyprctl hyprpaper reload ,"$img"
else
  echo "No image selected"
fi

