#!/bin/bash


if [[ ! -d $dotfiles ]]
then
  echo "No dotfiles present"
  return 1
fi

cd $dotfiles

if [[ -z "$(git status --porcelain)" ]]
then
  git pull origin master
else
  git status -s
  read -p "Modified or untracked files found, commit them? [y/n]: " commit
fi

if [[ $commit = 'y' || $commit = "yes" ]]
then
  git stash
  git pull origin master
  git stash apply
  git add .
  git commit -m "Automatic sync $(date)"
  git push origin master
elif [[ $commit = 'n' || $commit = "no" ]]
then
  echo "Skipping commit"
  git stash
  git pull origin master
  git stash apply
else
  echo "Invalid option, please commit files or skip."
  cd -
  exit 1
fi

cd -

