name: Test-Scripts

on: push

jobs:
  test-install-functions:
    name: test install functions
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: run test script
        run: ./tests/function_tests.sh

  test-preset-main:
    name: preset main
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test preset main
        run: ./setupscripts/setup preset main apt

  test-preset-server:
    name: preset server
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test preset server
        run: ./setupscripts/setup preset server apt

  test-preset-bare:
    name: preset bare
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test preset bare
        run: ./setupscripts/setup preset bare apt

  test-custom:
    name: test custom install
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test custom install
        run: ./setupscripts/setup bash git fail vim

