name: test-scripts

on: push

jobs:
  test-scripts:
    name: test on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test dracula install
        run: ./setupscripts/dracula_install.sh


      - name: test vim setup
        run: ./setupscripts/vim_setup.sh

  test-init-setup0:
    name: test init_setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test sudo+vim
        run: sudo ./setupscripts/init_setup.sh -sv ubuntu

  test-init-setup1:
    name: test init_setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3


  test-init-setup2:
    name: test init_setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test sudo 
        run: sudo ./setupscripts/init_setup.sh -s ubuntu


  test-init-setup3:
    name: test init_setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test vim 
        run: sudo ./setupscripts/init_setup.sh -v


  test-init-setup4:
    name: test init_setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test basic 
        run: sudo ./setupscripts/init_setup.sh 

  test-fedora:
    name: test on fedora
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v3

      - name: make fedora container 
        run: sudo docker run -it --name test -d fedora

      - name: copy files
        run: sudo docker cp ./setupscripts/init_setup.sh test:/home/

      - name: test script
        run: sudo docker exec test /home/init_setup.sh -sv fedora
        
  

        
