name: test-scripts

on: push

jobs:
  test:
    name: test scripts
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test dracula install
        run: ./setupscripts/dracula_install.sh

      - name: test ubuntu setup
        run: ./setupscripts/dracula_install.sh

      - name: test vim_setup.sh
        run: ./setupscripts/dracula_install.sh

        
