name: Test-Scripts

on: push

jobs:
  init-setup-vim-apps:
    name: init_setup.sh With App and Vim Install
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test sudo+vim
        run: sudo ./setupscripts/init_setup.sh -sv apt


  init-setup-apps:
    name: init_setup.sh With App Install
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test sudo 
        run: sudo ./setupscripts/init_setup.sh -s apt


  init-setup-vim:
    name: init_setup.sh With Vim Install
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test vim 
        run: ./setupscripts/init_setup.sh -v

      - name: show vim directory
        run: ls ~/.vim

      - name: show contents of vimrc
        run: cat ~/.vim/vimrc


  init-setup-basic:
    name: test init_setup.sh With Basic Install
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test basic install
        run: ./setupscripts/init_setup.sh 

      - name: show contents of bashrc
        run: cat ~/.bashrc

      - name: show contents of gitconfig
        run: cat ~/.gitconfig

      - name: show dracula directory
        run: ls ~/.vim/pack/themes/start/dracula

      - name: show contents of vimrc
        run: cat ~/.vim/vimrc

