name: test-scripts

on: push

jobs:
  test-scripts:
    name: test on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test dracula install
        run: ./setupscripts/dracula_install.sh

  test-init-setup0:
    name: test init_setup with apps and vim install
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test sudo+vim
        run: sudo ./setupscripts/init_setup.sh -sv ubuntu


  test-init-setup1:
    name: test init_setup with just application install
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test sudo 
        run: sudo ./setupscripts/init_setup.sh -s ubuntu


  test-init-setup3:
    name: test init_setup with vim install
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test vim 
        run: ./setupscripts/init_setup.sh -v

      - name: show vim directory
        run: ls ~/.vim

      - name: show contents of vimrc
        run: cat ~/.vim/vimrc


  test-init-setup4:
    name: test init_setup basic
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: test basic 
        run: ./setupscripts/init_setup.sh 

      - name: show contents of bashrc
        run: cat ~/.bashrc

      - name: show contents of gitconfig
        run: cat ~/.gitconfig

      - name: show bin directory
        run: ls ~/.local/bin

      - name: show contents of vimrc
        run: cat ~/.vim/vimrc

